server:
  port: 8080

spring:
  #  datasource:
  #    url: jdbc:h2:file:./data/appserver
  #    username: sa
  ##    password:
  #    driver-class-name: org.h2.Driver
  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

  kafka:
    enabled: false
    bootstrap-servers: "localhost:9092"
    topics:
      message-writer: "sample-topic-001"

logging:
  level:
    org.springframework.security: DEBUG